### ISSUE TITLE
IDA.exe 7.0 crashed after putting the plugin DLL in plugins dir.

### ISSUE THREAD

**Issue by jackchentwkh** [ecx86/classinformer-ida7#1]
I put the DLLs into the plugins sub dir of IDA. then start ida.exe. and it crashed and show a error msg window telling that it encountered a unknown error and it will close itself and save a dump file.
I then remove those DLLs and restart the IDA again. it no longer crashed.

**Comment by rcx** [comment]
please post the crash dump. also, attach a debugger and give me a stack trace of where it's crashing please.
  
if you can, compile in debug mode too and pass me the crash report.

**Comment by rcx** [comment]
@jackchentwkh OK, i have attached some debug builds to the releases. please use those and report back with the error. thanks

**Comment by jackchentwkh** [comment]
I use ollydbg but it can't load ida.exe under win10 x64.
when I use the debug version DLLs, ida can start without crash.
it can even load a old classinformer database.
but when running the plugin, 
the plugin crashed, ida remains working.
here is what I got from IDA's status window.

-----------------------------------------------------------------------------------------

>> Class Informer: v: 2.4, built: Jan  7 2018, By Sirmabus
Caching '[Class Informer]'... ok

>> Class Informer: v: 2.4, built: Jan  7 2018, By Sirmabus
Working..

Processing C/C++ ctor & dtor tables.
00C1B5A7 C: "__cinit", 145 bytes.
00C1B6E2 I: "__initterm", 28 bytes.
00C1B6FE E: "__initterm_e", 34 bytes.
 
00C1B6E2 processInitterm: "__initterm" 
  00C1B808 "__initterm" xref.
  00C1B7FE Two instruction pattern match #0
    0115BB6C to 0115BB84 DTOR table.
  00C1B819 "__initterm" xref.
  00C1B80F Two instruction pattern match #0
    0115BB88 to 0115BB8C DTOR table.
 
00C1B6FE processInitterm: "__initterm_e" 
  00C1B5DB "__initterm_e" xref.
  00C1B5D1 Two instruction pattern match #0
    0115BB48 to 0115BB68 CTOR table.
 
Processing time: 0.52 seconds.

Scanning for for RTTI Complete Object Locators.
 N: ".rdata", A: 0115B624 - 01515000, S: 3.7 MB.
 N: ".data", A: 01515000 - 02364000, S: 14.3 MB.
 N: "minATL", A: 02364000 - 02365000, S: 4 KB.
     Total COL: 1,367
COL scan time: 7.271

Scanning for vftables.
 N: ".rdata", A: 0115B624-01515000, S: 3.7 MB.
 Count: 1,367
 N: ".data", A: 01515000-02364000, S: 14.3 MB.
 N: "minATL", A: 02364000-02365000, S: 4 KB.
vftable scan time: 3.823
 

=========== Stats ===========
  RTTI vftables: 1367
Functions fixed: 0
Processing time: 11.68 seconds
Done.

** Exception in CORE_Process()! ***

**Comment by jackchentwkh** [comment]
ok, I tried the lastest x64dbg to load ida.exe. and interesting that both debug and release version of your DLL no longer crash the ida.  and the plugin works. but after plugin finish its job. I tried to close the database and then ida will hang, no response. there is no error message. I have to close ida with x64dbg.
after closing ida, the database was still unpacked. 
then I close x64dbg and run idapro directly. This time I can get in ida and use classinformer plug in. 
I then close the database. ida closed the database.
then I close ida. and relaunch ida again, but this time I couldn't find the classinformer plugin in the menu. 
seems the DLL still has some sort of issue but I can't reproduce it everytime.

**Comment by rcx** [comment]
Hmm...are you on the leaked IDA, or a proper one?

**Comment by jackchentwkh** [comment]
ho.... Lets say that my IDA is not upgraded to SP1.

**Comment by rcx** [comment]
that's ok. however, I can't solve this crash unless I can reproduce it. i need a dump or traceback.

**Comment by Hmmaster** [comment]
did you make config setting or maybe you missed that 
some time it happens

**Comment by rcx** [comment]
Closing this issue as it's almost 2 years old and I don't have any way to reproduce it
