### ISSUE TITLE
Compiler Error C2065, C2664

### ISSUE THREAD

**Issue by slava-aes** [ecx86/classinformer-ida7#12]
Hi, I'm having some problems compiling the project on visual studio, namely these two errors:

Error C2065 cin: undeclared PlugIn ID Main.cpp 92
at:
`if (strcmp(inf.procname, "metapc") == 0) // (ph.id == PLFM_386)`

so it seems that inf is undefined

and 
Severity Code Description Project File String Suppression Status
Error C2664 "QT::Dialog::Dialog(const QT::QDialog &)": cannot convert argument 2 from "int" to "QT::Qt::windowflags" PlugIn MainDialog.cppMainDialog.cpp 13

at:
`MainDialog::MainDialog(BOOL &optionPlaceStructs, BOOL &optionProcessStatic, BOOL &optionAudioOnDone, SegSelect::segments **segs) : QDialog(QApplication::activeWindow(), 0)`

**Comment by rcx** [comment]
Hi, what version of IDA are you compiling against?

ecx

**Comment by slava-aes** [comment]
7.3, I moved to 7.5 and reinstalled QT, it was probably due to a falty installation. Works fine now, although I got some errors while compiling at first, nothing worth mentioning though.

**Comment by rcx** [comment]
OK. Also FYI there is an official build for 7.5 by the actual developer of
classinformer and not me. glad it worked out👍
