### ISSUE TITLE
Progress indicator

### ISSUE THREAD

**Issue by fireundubh** [ecx86/classinformer-ida7#3]
I'm currently running Class Informer on a ~1 GB project. The "please wait" dialog has been up for a couple of hours. The progress bar is continuously animating. First time using Class Informer. Does this process just take a while? Or did the plugin get into a state where the loop never completes or throws an exception?

**Comment by rcx** [comment]
To be honest, I’m not quite sure. I suspect it has indeed hung; however, I
only ported this project from IDA 6.8 so I’m not too familiar with the
implementation details specifically. Does it hang on the IDA 6.8 version
too?

**Comment by fireundubh** [comment]
I let it run overnight. 5.29 hours!

```
>> Class Informer: v: 2.4, built: Jan  7 2018, By Sirmabus
Working..

Processing C/C++ ctor & dtor tables.
0000000180E594EC I: "_initterm", 6 bytes.
0000000180E594F2 E: "_initterm_e", 6 bytes.
0000000181E13658 import: "__imp__initterm".
0000000181E13648 import: "__imp__initterm_e".
 
0000000180E594EC processInitterm: "_initterm" 
  0000000180C61E66 "_initterm" xref.
  0000000180C61E58 Two instruction pattern match #0
    0000000181E13D48 to 0000000181E274A8 CTOR/DTOR table.
 
0000000180E594F2 processInitterm: "_initterm_e" 
  0000000180C61E46 "_initterm_e" xref.
  0000000180C61E38 Two instruction pattern match #0
    0000000181E274B0 to 0000000181E274C8 CTOR/DTOR table.
 
0000000181E13648 processInitterm: "__imp__initterm_e" 
 
0000000181E13658 processInitterm: "__imp__initterm" 
 
Processing time: 0.23 seconds.

Scanning for for RTTI Complete Object Locators.
 N: ".rdata", A: 0000000181E13D38 - 0000000182604000, S: 7.9 MB.
 N: ".data", A: 0000000182604000 - 0000000183415000, S: 14.1 MB.
 N: ".pdata", A: 0000000183415000 - 00000001835C1000, S: 1.7 MB.
 N: ".gfids", A: 00000001835C1000 - 00000001835C2000, S: 4 KB.
 N: ".tls", A: 00000001835C2000 - 00000001835C3000, S: 4 KB.
     Total COL: 14,698

Scanning for vftables.
 N: ".rdata", A: 0000000181E13D38-0000000182604000, S: 7.9 MB.
0000000181E9A750 ** Vftable attached to this COL, error?
0000000181F8CE08 ** Vftable attached to this COL, error?
 Count: 14,698
 N: ".data", A: 0000000182604000-0000000183415000, S: 14.1 MB.
 N: ".pdata", A: 0000000183415000-00000001835C1000, S: 1.7 MB.
 N: ".gfids", A: 00000001835C1000-00000001835C2000, S: 4 KB.
 N: ".tls", A: 00000001835C2000-00000001835C3000, S: 4 KB.
 

=========== Stats ===========
  RTTI vftables: 14696
Functions fixed: 2
Processing time: 5.29 hours
Done.

Caching '[Class Informer]'... ok
```

I think it'd be nice if the progress dialog showed more progress data, so you have some indication the plugin is still working. Elapsed time? Estimated time left? A running log of what's happening?

**Comment by rcx** [comment]
I'm surprised it took that long. What was the input file like? Could you take screenshot of segments?

**Comment by fireundubh** [comment]
Here's a screenshot of the segments:

![Segments](https://i.imgur.com/hw0ZYH0.jpg)

**Comment by fireundubh** [comment]
~@ecx86 This is totally OT, but I see that you've ported some of sirmabus' other plugins. Do you think you'll get around to Function String Associate?~

**Comment by fireundubh** [comment]
@ecx86 I ported [Function String Associate](https://sourceforge.net/projects/idafunctionstringassociate/) myself.

You can find it here: [fireundubh/IDA7-FunctionStringAssociate](https://github.com/fireundubh/IDA7-FunctionStringAssociate)

Let me know what's broken. 😆

**Comment by rcx** [comment]
These are an easy fix. Seems like Utility.obj was compiled with /MT flag,
while your project is configured for /MD. You should change that in your
Project settings under C/C++ -> code generation. Once you get it working,
please open source it! Best of luck.

**Comment by rcx** [comment]
Oh, it seems you’ve already fixed it.

**Comment by fireundubh** [comment]
> Oh, it seems you’ve already fixed it.

Yeah, thanks, man! The port seems to work. It at least finds and excludes all the "Microsoft VisualC" strings, but not much else. Maybe something is internally wrong. Let me know how it works for you!

Sorry for the derail, but GitHub doesn't offer messaging anymore. 😢

**Comment by Lopol2010** [comment]
It took all night and i give up. BTW my input file is minecraft.windows.exe lol. I try to disable some segments before start Class-Informer so i think ```.rdata``` is problem, other segments done in 1 second.

**Comment by Lopol2010** [comment]
I found solution(i think:). Downlad IDA 6.8 and Class-Informer from folder called IDA 6.7 (this folder from Class-Informer 2.2 zip archive i think)
1. It took ~10sec to finish
2. It shows kind of progress instead of "AU: Idle" at the left bottom corner

**Comment by rcx** [comment]
Honestly I have no idea why it hangs, people have been reporting this for months and I don't know how to reproduce it.

**Comment by Lopol2010** [comment]
I tried several EXE's and plugin work on some of them. If you want there is problematic exe
[Minecraft.Windows.exe.zip](https://github.com/ecx86/classinformer-ida7/files/2143416/Minecraft.Windows.exe.zip)

 (or should i send IDA database 600mb?)

**Comment by rcx** [comment]
Thanks, I will look into this once I have the time.

**Comment by rcx** [comment]
Do you have any smaller exes which are problematic? This one is taking very long to analyze.

**Comment by gir489** [comment]
I'm also having this issue on Fallout 4's EXE. Class Informat on 6.8 used to take ~3 minutes. This one ran for hours and got nothing.

**Comment by gir489** [comment]
Here is my log:

Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] 
IDAPython 64-bit v1.7.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
---------------------------------------------------------------------------------------------
failed to add structure type '_stat64i32': name is already used
failed to add structure type '_stat64i32': name is already used
failed to add structure type '_stat64i32': name is already used
failed to add structure type '_stat64i32': name is already used
Using FLIRT signature: SEH for vc64 7-14
failed to add structure type '_stat64i32': name is already used
failed to add structure type '_stat64i32': name is already used
Propagating type information...
Function argument information has been propagated
The initial autoanalysis has been finished.

>> Class Informer: v: 2.4, built: Jan  7 2018, By Sirmabus
Working..

Processing C/C++ ctor & dtor tables.
000000014295CE8C E: "_initterm_e", 6 bytes.
000000014295CE92 I: "_initterm", 6 bytes.
0000000142C41F88 import: "__imp__initterm".
0000000142C41F80 import: "__imp__initterm_e".
 
000000014295CE8C processInitterm: "_initterm_e" 
  000000014295C061 "_initterm_e" xref.
  000000014295C053 Two instruction pattern match #0
    0000000142C728A0 to 0000000142C728C8 CTOR/DTOR table.
 
000000014295CE92 processInitterm: "_initterm" 
  000000014295C097 "_initterm" xref.
  000000014295C089 Two instruction pattern match #0
    0000000142C426A0 to 0000000142C72898 CTOR/DTOR table.
 
0000000142C41F80 processInitterm: "__imp__initterm_e" 
 
0000000142C41F88 processInitterm: "__imp__initterm" 
 
Processing time: 17.18 seconds.

Scanning for for RTTI Complete Object Locators.
 N: ".rdata", A: 0000000142C42698 - 0000000143703000, S: 10.8 MB.
     Total COL: 11,953

Scanning for vftables.
 N: ".rdata", A: 0000000142C42698-0000000143703000, S: 10.8 MB.
0000000142C72B08 ** Vftable attached to this COL, error?
0000000142D9F278 ** Vftable attached to this COL, error?
0000000142D9F298 ** Vftable attached to this COL, error?
0000000142D9F2B8 ** Vftable attached to this COL, error?
0000000142D9F2F8 ** Vftable attached to this COL, error?
0000000142D9F310 ** Vftable attached to this COL, error?
0000000142D9F330 ** Vftable attached to this COL, error?
0000000142D9F350 ** Vftable attached to this COL, error?
0000000142D9F370 ** Vftable attached to this COL, error?
0000000142D9F738 ** Vftable attached to this COL, error?
0000000142D9F758 ** Vftable attached to this COL, error?
0000000142D9F778 ** Vftable attached to this COL, error?
0000000142D9F7B8 ** Vftable attached to this COL, error?
0000000142D9F7D0 ** Vftable attached to this COL, error?
0000000142D9F7F0 ** Vftable attached to this COL, error?
0000000142D9F810 ** Vftable attached to this COL, error?
0000000142D9F830 ** Vftable attached to this COL, error?
0000000142D9FB38 ** Vftable attached to this COL, error?
0000000142D9FB58 ** Vftable attached to this COL, error?
0000000142D9FB78 ** Vftable attached to this COL, error?
0000000142D9FBB8 ** Vftable attached to this COL, error?
0000000142D9FBD0 ** Vftable attached to this COL, error?
0000000142D9FBF0 ** Vftable attached to this COL, error?
0000000142D9FC10 ** Vftable attached to this COL, error?
0000000142D9FC30 ** Vftable attached to this COL, error?
0000000142E34000 ** Vftable attached to this COL, error?
0000000142EBD440 ** Vftable attached to this COL, error?
0000000142ECB248 ** Vftable attached to this COL, error?
0000000142ECB288 ** Vftable attached to this COL, error?
0000000142ECB308 ** Vftable attached to this COL, error?
0000000142ECDB38 ** Vftable attached to this COL, error?
 Count: 11,953
 

=========== Stats ===========
  RTTI vftables: 11922
Functions fixed: 11250
Processing time: 1.45 hours
Done.

Caching '[Class Informer]'... ok

**Comment by ecx86** [comment]
I wonder if this is the problem `Vftable attached to this COL, error`

I will look into this

**Comment by rcx** [comment]
Sorry for taking so long, this has been fixed. The issue was that there would be names containing bad characters such as `<`, which would lock up this loop:

```C++
	for (int i = 0; i < 1000000; i++)
	{
		char buffer[MAXSTR]; buffer[SIZESTR(buffer)] = 0;
		_snprintf(buffer, SIZESTR(buffer), "%s_%d", name, i);
		if (set_name(ea, buffer, (SN_NON_AUTO | SN_NOWARN))) {
			return(TRUE);
		}
	}
```

**Comment by fireundubh** [comment]
Thanks! What used to take hours now takes seconds. 👍
