### ISSUE TITLE
Waited about 5 hours with "please wait" and when it completed no tab

### ISSUE THREAD

**Issue by ghost** [ecx86/classinformer-ida7#4]
So I just waited about 5 hours for it to finish everything and when it completed, there's no tab. What am I supposed to do?

**Comment by v0idst4r** [comment]
I'm using IDA v7.0.0.170914 64bit with the 64bit dll

**Comment by v0idst4r** [comment]
I'm so damn pissed

**Comment by ajvpot** [comment]
please wait

**Comment by ghost** [comment]
Used CI 2.0 and IDA 6.8 instead.

**Comment by rcx** [comment]
Fixed
