### ISSUE TITLE
The specified procedure could not be found.

### ISSUE THREAD

**Issue by ghost** [ecx86/classinformer-ida7#5]
I've downloaded the plugin from the releases however when I run IDA I get the following error.

> LoadLibrary(C:\Program Files\IDA Freeware 7.0\plugins\IDA_ClassInformer_PlugIn64.dll) error: The specified procedure could not be found.
> C:\Program Files\IDA Freeware 7.0\plugins\IDA_ClassInformer_PlugIn64.dll: can't load file

The error also appears twice if that means anything.

Running IDA 7.0 Freeware

**Comment by rcx** [comment]
Freeware doesn't support plugins. Go get the full version of 7.0, how exactly I won't say ;)
