### ISSUE TITLE
error: The specified procedure could not be found. - can't load file

### ISSUE THREAD

**Issue by mr-mosh** [ecx86/classinformer-ida7#9]
Hello @rcx ,

Thanks for taking the time to backport the plugin to 7.0. Like you, I also cannot afford to go beyond that. In fact, I'm using the Free 7.0 version, which makes me wonder if plugins would be supported at all. The info page on https://www.hex-rays.com/products/ida/support/download_freeware/ doesn't say either way, and I can only find inconsistent messaging about it out there.

I've copied the two .dlls into the plugins directory, and edited the plugins.cfg as per the original instructions (mins the .plw file extension, they have in their instructions).

So, the errors I get specifically are:

"LoadLibrary(C:\Program Files\IDA Freeware 7.0\plugins\IDA_ClassInformer_PlugIn64.dll) error: The specified procedure could not be found.
C:\Program Files\IDA Freeware 7.0\plugins\IDA_ClassInformer_PlugIn64.dll: can't load file"

This line is displayed twice.

My plugins.cfg (located in the plugins directory) includes the following at the very bottom

; Sirmabus "Class Informer" plug-in
Class-Informer     IDA_ClassInformer_PlugIn64	Alt-2 	0

Note: I have also tried adding ".dll" to the config line above (the IDA templates don;t have .dll on them, yet the files are .dll). No difference.

So yes, I'm a bit stuck. Any ideas on whether this can be resolved please?

Thank.

**Comment by rcx** [comment]
Unfortunately, i don't think freeware version is supported by this plugin but if you look online, there is a widely-known crack of ida 7.0. Thanks for taking the time to write this issue, I am glad people are using the code still.
